// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkdpunhjiwebpennkuqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZHB1bmhqaXdlYnBlbm5rdXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDQ2MDAsImV4cCI6MjA2Njc4MDYwMH0.ldc9tTdTAmqYLvsJRApWkfmu1sdPvb3LvcmHJL_hISE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);